-- =========================================================
-- LIBRA - Digital Library Management System
-- Supabase PostgreSQL Database Schema & Initial Seeds
-- =========================================================

-- Enable UUID extension if needed in future
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. Users Table
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 2. Books Table
CREATE TABLE IF NOT EXISTS books (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(20) UNIQUE NOT NULL,
    title VARCHAR(255) NOT NULL,
    author VARCHAR(255) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'available' CHECK (status IN ('available', 'borrowed', 'overdue')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 3. Issues Table
CREATE TABLE IF NOT EXISTS issues (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id BIGINT NOT NULL REFERENCES books(id) ON DELETE RESTRICT,
    borrower VARCHAR(100) NOT NULL,
    issued_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    due_at TIMESTAMPTZ NOT NULL,
    returned_at TIMESTAMPTZ,
    fine_amount NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Performance Indexes
CREATE INDEX IF NOT EXISTS idx_users_username ON users(username);
CREATE INDEX IF NOT EXISTS idx_books_code ON books(code);
CREATE INDEX IF NOT EXISTS idx_books_status ON books(status);
CREATE INDEX IF NOT EXISTS idx_issues_book_id ON issues(book_id);
CREATE INDEX IF NOT EXISTS idx_issues_returned_at ON issues(returned_at);

-- Row Level Security (RLS) configuration
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE books ENABLE ROW LEVEL SECURITY;
ALTER TABLE issues ENABLE ROW LEVEL SECURITY;

-- Allow full access for backend service and authorized server clients
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies WHERE tablename = 'users' AND policyname = 'Allow server access to users'
    ) THEN
        CREATE POLICY "Allow server access to users" ON users FOR ALL USING (true) WITH CHECK (true);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_policies WHERE tablename = 'books' AND policyname = 'Allow server access to books'
    ) THEN
        CREATE POLICY "Allow server access to books" ON books FOR ALL USING (true) WITH CHECK (true);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_policies WHERE tablename = 'issues' AND policyname = 'Allow server access to issues'
    ) THEN
        CREATE POLICY "Allow server access to issues" ON issues FOR ALL USING (true) WITH CHECK (true);
    END IF;
END $$;

-- =========================================================
-- Initial Seeds
-- =========================================================

-- Admin User (password: admin123)
INSERT INTO users (username, password_hash)
VALUES ('admin', 'f7b192c308e9a2b847c9f80164c92b45$8bf88d7a47c2a30c57f7fbd840035b31eaeda7d8483564fd0b604bb95c33d062')
ON CONFLICT (username) DO NOTHING;

-- Initial Catalog Books
INSERT INTO books (id, code, title, author, status) VALUES
(1, 'B001', 'Introduction to Python', 'Mark Lutz', 'available'),
(2, 'B002', 'Database System Concepts', 'Abraham Silberschatz', 'borrowed'),
(3, 'B003', 'Computer Networks', 'Andrew S. Tanenbaum', 'available'),
(4, 'B004', 'Software Engineering', 'Ian Sommerville', 'borrowed'),
(5, 'B005', 'Data Structures and Algorithms', 'Robert Lafore', 'available'),
(6, 'B006', 'Web Technologies', 'Uttam K. Roy', 'available'),
(7, 'B007', 'Operating Systems', 'Abraham Silberschatz', 'available'),
(8, 'B008', 'Computer Organization', 'Carl Hamacher', 'overdue')
ON CONFLICT (code) DO NOTHING;

-- Synchronize Identity Sequence for books
SELECT setval(pg_get_serial_sequence('books', 'id'), COALESCE(MAX(id), 1)) FROM books;

-- Initial Active Issues
-- Note: Loan period is 14 days
INSERT INTO issues (id, book_id, borrower, issued_at, due_at, returned_at, fine_amount) VALUES
(1, 2, 'Student A', NOW() - INTERVAL '4 days', NOW() + INTERVAL '10 days', NULL, 0.00),
(2, 4, 'Student B', NOW() - INTERVAL '6 days', NOW() + INTERVAL '8 days', NULL, 0.00),
(3, 8, 'Student C', NOW() - INTERVAL '20 days', NOW() - INTERVAL '6 days', NULL, 0.00)
ON CONFLICT (id) DO NOTHING;

-- Synchronize Identity Sequence for issues
SELECT setval(pg_get_serial_sequence('issues', 'id'), COALESCE(MAX(id), 1)) FROM issues;
